language: python

python:
 - 3.6
 - 3.5
 - 3.7

before_install:
 - wget https://www4.stat.ncsu.edu/~boos/var.select/diabetes.rwrite1.txt
 - mv diabetes.rwrite1.txt diabetes.data

script:
 - python3 CEBD1100_Homework7_ThibaultPasturel.py --help